Models/ErrorViewModel.cs
using System;

namespace highestRootApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using highestRootApp.Models;

namespace highestRootApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/squareRootController.cs
using System;
using Microsoft.AspNetCore.Mvc;

namespace squareRoot.Controllers
{
    public class squareRootController : Controller
    {
        [HttpGet]
        public ActionResult square()
        {
            return View();
        }

        [HttpPost]
        public ActionResult square(string firstNumber, string secondNumber)
        {
            

            int playerOne = int.Parse(firstNumber);
            int playerTwo = int.Parse(secondNumber);

            double sqr1 = Math.Sqrt(playerOne);
            double sqr2 = Math.Sqrt(playerTwo);

            double result1 = sqr1;
            double result2 = sqr2;

            ViewBag.Result1 = result1;
            ViewBag.Result2 = result2;
            return View();
        }
    }
    
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - highestRootApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">highestRootApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="squareRoot" asp-action="square">Get Highest Root</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - highestRootApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/squareRoot/square.cshtml
@{
    ViewData["Title"] = "Square Root";
}

<div class="text-center">
    <h1 class="display-4">Welcome To The Highest Square Root App</h1>
</div>

@{
    if(ViewBag.Result1 != null && ViewBag.Result2 != null)
    {
        if(ViewBag.Result1 == ViewBag.Result2)
        {
         <div>
            <p>you both have same square root of : @ViewBag.Result1 and @ViewBag.Result2, please try again</p>
        </div>
        }

      else  if(ViewBag.Result1 <= 0 || ViewBag.Result2 <= 0)
        {
            <h6>Error, Please Enter Numbers Greater Than ZERO (0)</h6>
        }

        else if(ViewBag.Result1 > ViewBag.Result2)
        {
           <div>
            <p>Player One has the highest square root of : @ViewBag.Result1</p>
        </div> 
        }

        else if(ViewBag.Result1 < ViewBag.Result2)
        {
           <div>
            <p>Player Two has the highest square root of : @ViewBag.Result2</p>
        </div> 
        }
        
    }
}

<div>
    <form asp-controller="squareRoot" asp-action="square" method="POST">
        <input type="number" placeholder="Player One Number" name="firstNumber">
        <input type="number" placeholder="Player Two Number" name="secondNumber">
        <button>Submit</button>
    </form>
</div>